services:

  test-postgres:
    image: "postgres:16-alpine"
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  test-redis:
    image: redis:7.2
    ports:
      - ${REDIS_PORT}:6379

  test-minio:
    image: minio/minio
    entrypoint: sh
    command: >
      -c 'mkdir -p /data/"${MINIO_BUCKET}"
      && minio server /data'
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - ${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}
    environment:
      MINIO_ROOT_USER: "${MINIO_LOGIN}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
      MINIO_ADDRESS: ":${MINIO_PORT}"
      MINIO_CONSOLE_ADDRESS: ":${MINIO_CONSOLE_PORT}"

  test-backend:
    profiles: ["full"]
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - test.env
    environment:
      POSTGRES_HOST: test-postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: test-redis
      MINIO_HOST: test-minio
    depends_on:
      test-postgres:
        condition: service_healthy
      test-redis:
        condition: service_started
      test-minio:
        condition: service_started