FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev postgresql-dev

RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-dev

COPY src/ ./src/

EXPOSE 8000

CMD ["uvicorn", "cloud_storage.main:create_app", "--host", "0.0.0.0", "--port", "8000"]
